name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Adjust if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      run: |
        echo $HEROKU_API_KEY | heroku login --username=$HEROKU_EMAIL --password-stdin
        heroku container:login

    - name: Build and Push Backend Docker Image
      working-directory: ./backend  # Adjust if necessary
      run: |
        heroku container:push web --app your-backend-app-name

    - name: Release Backend App
      run: |
        heroku container:release web --app your-backend-app-name

    - name: Build and Push Frontend Docker Image
      working-directory: ./frontend  # Adjust if necessary
      run: |
        heroku container:push web --app your-frontend-app-name

    - name: Release Frontend App
      run: |
        heroku container:release web --app your-frontend-app-name
