name: GCP Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    name: Build and Deploy to GCP (FRONT & BACKEND DEPL.)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        project_id: 'YOUR_PROJECT_ID'

    - name: Build Docker image (BackEnd)
      run: |
        docker build -t gcr.io/groove-437022/backend:${{ github.sha }} .

    - name: Build Docker image (FrontEnd)
      run: |
        docker build -t gcr.io/groove-437022/frontend:${{ github.sha }} .

    - name: Push Docker image (BackEnd)
      run: |
        docker push gcr.io/groove-437022/backend:${{ github.sha }}

    - name: Push Docker image (FrontEnd)
      run: |
        docker push gcr.io/groove-437022/frontend:${{ github.sha }}

    - name: Deploy to Cloud Run (BackEnd)
      run: |
        gcloud run deploy backend-service \
          --image gcr.io/groove-437022/backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Deploy to Cloud Run (FrontEnd)
      run: |
        gcloud run deploy frontend-service \
          --image gcr.io/groove-437022/frontend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
